language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_USER
    - secure: "GiYBEihaUGTPcTXMKlUbLnyuw7NavE0KWzZgz3rXlHhYHF7M/K7JWR0QQaWGx8cAR/wMv08ATsf2b5MilriPYQnd6kCMyLrP1YzoHMIKaSm7tWhmcE75WZ44IQdXS+mXIPpIDSKToH5dGFTz87hpMm58vgNnMwXj8xaWr4XM63IRGZwLbBXN6sUCTYhJ3j/suVfc092HjGTSTwlwjdaw93oJI4Cz55Q54ahtSRuIWdcnMIJbW5hbeSHC+LcVLYEnbkfB4LACNVK4Dvn6wXDFvTbZKy+tjTJjInXCo19KG+Blrm3C5iPG3N+pwIe8DB1ItuR1b+iRmtqOyi5/ktVE3NMgc73hteZdeNoAOTIqmzGL+QNjlhqeyRHcnlSKdPrw3d2Axz/cwagmwQmCebD5NnYr95fiyS4xtcUmrgJdGNA5HEKKwunhyfTFXWELMUAM1olh7lBUN9FlklCDDP79k3+GCYTwPJrYnRdqcMBiks3RylQbAWcqdffXYZVU5MaTC+NUQaIiXi7trZCkwiv5kl0KsO9uqiy9gyL6nJjdWzbT4ZGeRszMFzJ3zw5k62yAtwFvuQCBg7Rqs74LWF/N5NyUuunlxKNzz4Ey/MHJQE8qnqBWH4QQ90Z5NjCFnxOVG8EUAsdQlwUZEIAOZilUJpG7gmOCndJRse52e87Lv/0="
    # DEPLOY_HOST
    - secure: "CuGKMuD1BbCtGVVdJAFZ+9jIsK8xSIsrOrfhl13b+rOu+ucfATjrsLlgcLcH9OkUenDzkG0NHuyASpwpX/qL4RB8ZKuNNKEALA25Yzh/Zf94TkJRRZL4iEUR8341BawmTc8bY3Y8IjyBXIpSB9EeEOJisSabB68fTkgn/V8bgjNHTYCJcu8bkB6/SsD3t38VdwN4hujW5cYYKNkwyFeyQeoEBAWEnbZGeOAIRym8tgwRhmYrz8NnEikRCCdbKiJ8yd4P8NGBJJn8hrdiYwkBTmuu8RHu4JF5hMI1p0tA3qIiD3B1dqiM1INuLzhN5MDcBzwYaCbo9w+HZYe+4eQDbaGiNX2Y39CXis26yx2x+GGc4YhAtotbJEgEcXuz2ZZPvyyFEdjY2yKkZoRH3vDSyb+2RxcHg4IGoaFgby3eeFaTn9ym/W/9hQ/DcUBJse13HWDsFUERR7TyFQMXCWnBC324ZuTFN55n6AnyEQtIubaOSA82osE/puY53J0b85adDf5zzRBN2o+1IWbRamlbCSkupTugUstyZi1lYk5PDFKbg4nh7izsCZ7AqbxyJ/ElU3eU/6/R46+8FebXblwEqw1Jt0/vzvgsusGuSmTUAEoD1IShK94wn+uVb4wOOAeggu/mVcmWQOoRdz9ihTrT2ufgZ4R4IYkMiQH5mASLzfA="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

deploy:
  - provider: script
    script: .travis/deploy.sh build/default/qtudev-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"
  - provider: script
    script: .travis/deploy.sh build/default/qtudev-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
